[project]
name = "ai-cli-debugger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "psutil>=6.1.0",
    "rich>=13.9.4",
]
